currentBuild.displayName = "Final_Demo # "+currentBuild.number

   def getDockerTag(){
        def tag = sh script: 'git rev-parse HEAD', returnStdout: true
        return tag
        }
        

pipeline{
        agent any
	    tools { 
		maven 'maven'
		jdk 'jdk'
	    } 
        environment{
	    Docker_tag = getDockerTag()
        }
        
        stages{

            stage ('build') {
        steps{
            sh 'mvn -f /var/lib/jenkins/workspace/calc/Scientific-Calculator-master/Calculator compile'
        }
      }
      stage ('test') {
        steps{
            sh 'mvn -f /var/lib/jenkins/workspace/calc/Scientific-Calculator-master/Calculator test'
        }
      }
      stage('SonarQube Analysis') {
          steps{
		 sh 'java -version'
                sh 'mvn -f Scientific-Calculator-master/Calculator/pom.xml -D sonar.host.url=http://ec2-34-224-98-136.compute-1.amazonaws.com:9000/  -D sonar.language=java clean package sonar:sonar'
          }
}
             
                 
		
	
		
    }
	post {
        always {
            junit 'build/reports/**/*.xml'
        }
    }    
	       
	       
	      
    
}
