currentBuild.displayName = "Final_Demo # "+currentBuild.number

   def getDockerTag(){
        def tag = sh script: 'git rev-parse HEAD', returnStdout: true
        return tag
        }
        

pipeline{
        agent any
	    tools { 
		maven 'maven' 
	    } 
        environment{
	    Docker_tag = getDockerTag()
        }
        
        stages{

            stage ('build') {
        steps{
            sh 'mvn -f /var/lib/jenkins/workspace/calc/Scientific-Calculator-master/Calculator compile'
        }
      }
      stage ('test') {
        steps{
            sh "mvn -f /var/lib/jenkins/workspace/calc/Scientific-Calculator-master/Calculator test"
        }
      }
             
                 
		
	
		
    }
	       
	       
	       
	      
    
}
