currentBuild.displayName = "Final_Demo # "+currentBuild.number

   def getDockerTag(){
        def tag = sh script: 'git rev-parse HEAD', returnStdout: true
        return tag
        }
        

pipeline{
        agent any
	    tools { 
		maven 'maven'
		jdk 'jdk'
	    } 
        environment{
	    Docker_tag = getDockerTag()
        }
        
        stages{

            stage ('build') {
        steps{
            sh 'mvn -f /var/lib/jenkins/workspace/calc/Scientific-Calculator-master/Calculator compile'
        }
      }
      stage ('test') {
        steps{
            sh 'mvn -f /var/lib/jenkins/workspace/calc/Scientific-Calculator-master/Calculator test'
        }
      }
      stage('SonarQube Analysis') {
          steps{
//       withSonarQubeEnv('sonar') {
//       sh """/var/lib/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/SonarQube/bin/sonar-scanner \
//      -D sonar.projectVersion=1.0-SNAPSHOT \
//        -D sonar.login=admin \
//       -D sonar.password=admin \
//       -D sonar.projectBaseDir=/var/lib/jenkins/workspace/calc/ \
//         -D sonar.projectKey=spring-petclinic \
//         -D sonar.sourceEncoding=UTF-8 \
//         -D sonar.language=java \
//         -D sonar.sources=Scientific-Calculator-master/Calculator/src/main/java/io/michaelcane/ \
//         -D sonar.tests=Scientific-Calculator-master/Calculator/src/test/java/io/michaelcane/ \
//         -D sonar.java.binaries=. \
//         -D sonar.host.url=http://ec2-34-224-98-136.compute-1.amazonaws.com:9000/"""
//         }
		  sh "${scannerHome}/bin/sonar-scanner"
          }
}
             
                 
		
	
		
    }
	       
	       
	       
	      
    
}
